img <- matrix(1:195,ncol=1)
for(i in 1 : 100)
{
  img[i] <- paste(folder,'vraag',i,'.png',sep="")
}
img[101] <- paste(folder,'head-stap1.png',sep="")
img[102] <- paste(folder,'head-stap2.png',sep="")
img[103] <- paste(folder,'head-stap3.png',sep="")
img[104] <- paste(folder,'head-stap4.png',sep="")
img[105] <- paste(folder,'head-stap5.png',sep="")
img[106] <- paste(folder,'head-stap6.png',sep="")
img[107] <- paste(folder,'head-stap7.png',sep="")
img[108] <- paste(folder,'head-stap8.png',sep="")
img[109] <- paste(folder,'head-stap9.png',sep="")
img[110] <- paste(folder,'head-stap10.png',sep="")
#
img[111] <- paste(folder,'summ1a.png',sep="") 
img[112] <- paste(folder,'summ1b.png',sep="")
img[113] <- paste(folder,'summ1c.png',sep="")
img[114] <- paste(folder,'summ2a.png',sep="") 
img[115] <- paste(folder,'summ2b.png',sep="")
img[116] <- paste(folder,'summ2c.png',sep="")
img[117] <- paste(folder,'summ3a.png',sep="") 
img[118] <- paste(folder,'summ3b.png',sep="")
img[119] <- paste(folder,'summ3c.png',sep="")
img[120] <- paste(folder,'summ4a.png',sep="") 
img[121] <- paste(folder,'summ4b.png',sep="")
img[122] <- paste(folder,'summ4c.png',sep="")
img[123] <- paste(folder,'summ5a.png',sep="") 
img[124] <- paste(folder,'summ5b.png',sep="")
img[125] <- paste(folder,'summ5c.png',sep="")
img[126] <- paste(folder,'summ6a.png',sep="") 
img[127] <- paste(folder,'summ6b.png',sep="")
img[128] <- paste(folder,'summ6c.png',sep="")
img[129] <- paste(folder,'summ7a.png',sep="") 
img[130] <- paste(folder,'summ7b.png',sep="")
img[131] <- paste(folder,'summ7c.png',sep="")
img[132] <- paste(folder,'summ8a.png',sep="") 
img[133] <- paste(folder,'summ8b.png',sep="")
img[134] <- paste(folder,'summ8c.png',sep="")
img[135] <- paste(folder,'summ9a.png',sep="") 
img[136] <- paste(folder,'summ9b.png',sep="")
img[137] <- paste(folder,'summ9c.png',sep="")
img[138] <- paste(folder,'summ10a.png',sep="") 
img[139] <- paste(folder,'summ10b.png',sep="")
img[140] <- paste(folder,'summ10c.png',sep="")
#
img[141] <- paste(folder,'head-gevoel.png',sep="")
img[142] <- paste(folder,'summ-gevoel-a.png',sep="")
img[143] <- paste(folder,'summ-gevoel-b.png',sep="")
img[144] <- paste(folder,'summ-gevoel-c.png',sep="")
#
img[145] <- paste(folder,'head-houding.png',sep="")
img[146] <- paste(folder,'summ-houding-a.png',sep="")
img[147] <- paste(folder,'summ-houding-b.png',sep="")
img[148] <- paste(folder,'summ-houding-c.png',sep="")
#
img[149] <- paste(folder,'head-orgkenmerk.png',sep="")
img[150] <- paste(folder,'summokenmerka.png',sep="")
img[151] <- paste(folder,'summokenmerkb.png',sep="")
img[152] <- paste(folder,'summokenmerkc.png',sep="")
#
img[153] <- paste(folder,'head-gedrag.png',sep="")
img[154] <- paste(folder,'summgedraga.png',sep="")
img[155] <- paste(folder,'summgedragb.png',sep="")
img[156] <- paste(folder,'summgedragc.png',sep="")
#
img[157] <- paste(folder,'head-effect.png',sep="")
img[158] <- paste(folder,'summeffecta.png',sep="")
img[159] <- paste(folder,'summeffectb.png',sep="")
img[160] <- paste(folder,'summeffectc.png',sep="")
#
img[161] <- paste(folder,'head-vitaal.png',sep="")
img[162] <- paste(folder,'summvitaal1.png',sep="")
img[163] <- paste(folder,'summvitaal2.png',sep="")
#
img[164] <- paste(folder,'head-duurzaam.png',sep="")
img[165] <- paste(folder,'summduurzaam1.png',sep="")
img[166] <- paste(folder,'summduurzaam2.png',sep="")
#
img[167] <- paste(folder,'head-transformatie.png',sep="")
img[168] <- paste(folder,'summtransformatiea.png',sep="")
img[169] <- paste(folder,'summtransformatieb.png',sep="")
img[170] <- paste(folder,'summtransformatiec.png',sep="")
#
img[171] <- paste(folder,'head-prestatie.png',sep="")
img[172] <- paste(folder,'summprestatiea.png',sep="")
img[173] <- paste(folder,'summprestatieb.png',sep="")
#
img[174] <- paste(folder,'head-waarden.png',sep="")
img[175] <- paste(folder,'summwaardena.png',sep="")
img[176] <- paste(folder,'summwaardenb.png',sep="")
#
img[177] <- paste(folder,"summosteps.png",sep="")
img[178] <- paste(folder,"summbsteps.png",sep="")
img[179] <- paste(folder,'summ10steps.png',sep="")
img[180] <- paste(folder,'summgedrag.png',sep="")
img[181] <- paste(folder,'summdimensie.png',sep="")
img[182] <- paste(folder,'kfactoren.png',sep="")
#
img[183] <- paste(default_images,"team_change.png",sep="")
img[184] <- paste(default_images,"sturen-op-softcontrols.jpg",sep="")
img[185] <- paste(default_images,"zelfbeeld.jpg",sep="")
img[186] <- paste(default_images,"i_change.png",sep="")
#
img[187] <- paste(folder,'matrix-10stappen.png',sep="")
img[188] <- paste(folder,"matrix-5kfactoren.png",sep="")
img[189] <- paste(folder,"matrix-4dimensies.png",sep="")
img[190] <- paste(folder,"matrix-5specials.png",sep="")
img[191] <- paste(folder,"matrix-3hooglaag.png",sep="")
#
img[192] <- paste(default_images,"schema-10r.jpg",sep="")
img[193] <- paste(default_images,"4U-CHANGE.png",sep="")
img[194] <- paste(default_images,"01-signaleren-analyseren.PNG",sep="")
img[195] <- paste(default_images,"00-voorblad-indicatoren.png",sep="")
img[196] <- paste(default_images,"t-change-voorpagina.jpg",sep="")
#
