<?php 

/**
 * This stylesheet was formerly the default used in the demonstrated 
 * phpMyEdit forms, however it became somewhat difficult to maintain.
 * This stylesheet is very complex. Make changes carefully.
 * This stylesheet follows the phpMyEdit style class policy (60+ style classes).
 * New, undocumented styleclasses may have crept into phpMyEdit.
 * If it does not meet your needs, use /style/generic.php instead.
 * [A|C|P] refers to page modes Add, Change, coPy.
*/

// $cfg['bdr_bottom'] = 1; // puts a border on the bottom cell in List mode
// $cfg['bdr_bottom'] = 4; // puts a border on all 4 edges of each cell in List mode

if(empty($cfg['bdr_bottom'])) { $cfg['bdr_bottom'] = 1; }

$_TWEAK = $cfg['bdr_bottom'] != 4 ? '-bottom' : '';

$opts['border_style']    = "border$_TWEAK:1px solid #003366;\n";

$cfg['family1']          = 'verdana,helvetica,arial,sans-serif'; // Affects most tags

$cfg['family2']          = 'arial,verdana,helvetica,sans-serif'; // Affects H3 tags

$cfg['size']             = 'x-small'; // Affects most tags

// Font colors configured as variables are changed depending on page mode.

$cfg['fcolor1'] = '#000000'; // INPUT, SELECT, TEXTAREA, etc. [A|C|P]

$cfg['fcolor3'] = '#004CCA'; // Clickable URL/mailto links

$cfg['fcolor4'] = '#004CCA'; // [A|C|P] Help: td.pme-help-0-right-justify, td.pme-help-0, td.pme-help-1-right-justify, td.pme-help-1

$cfg['row_nav_bgcolor'] = '#6699cc'; // TABLE default + navigation table row bgColor (Prev/Add/Next)

$cfg['bdr_bot_color']   = '#003366';   // Redefined below based on page mode

$cfg['valign'] = "vertical-align:middle;\n"; // Note newline. Redefined below based on page mode

/**
 * Over-ride certain colors depending on page mode (operation: Add, Change, etc.)
 */

switch(trim($operation))
{
   Case $opts['mfg']['oper_label']: // this label manually derived (not generated by phpMyEdit)
		$cfg['bgcolor0'] = '#ffffff'; // Alternating row bgColor aliceblue
		$cfg['bgcolor1'] = '#f0f8ff'; // Alternating row bgColor
		// $cfg['valign']   = "vertical-align:top;\n"; // <-- Note the newline
		break;
   Case 'Delete':
      $cfg['bgcolor1']      = '#cc0000';
      $cfg['bdr_bot_color'] = '#cc0000';
      $cfg['fcolor1']       = '#ffffff';
      $cfg['fcolor3']       = '#ffffff';
      $cfg['bgcolor0']      = '#cc0000';
      break;
   Case 'Add':
   Case 'Added':
   Case 'Apply':
      $cfg['bdr_bot_color'] = '#f0f0f0'; // Hide bottom-border
      $cfg['bgcolor0']      = '#f0f0f0';
      $cfg['bgcolor1']      = '#f0f0f0';
      break;
   Case 'Change':
   Case 'Changed':
      $cfg['bdr_bot_color'] = '#f0f0f0'; // Hide bottom-border
      $cfg['bgcolor0']      = '#f0f0f0';
      $cfg['bgcolor1']      = '#f0f0f0';
      break;
   Case 'Copy':
      $cfg['bdr_bot_color'] = '#f0f0f0'; // Hide bottom-border
      $cfg['bgcolor0']      = '#f0f0f0';
      $cfg['bgcolor1']      = '#f0f0f0';
      break;
   Case 'View':
      $cfg['bdr_bot_color'] = '#ffffff'; // Hide bottom-border
      $cfg['bgcolor0']      = '#ffffff';
      $cfg['bgcolor1']      = '#ffffff';
      break;
	Case 'update':
			$cfg['bgcolor0'] = '#ffffff';
			$cfg['bgcolor1'] = '#f0f8ff';
		break;
   default:
      break;
};

?>

<style type="text/css">
<!--

/* PHP-generated (after analyzing the current page mode  */

a{
background-color:transparent;
color:#000000;
}

a:hover{
background-color:transparent;
color:#ff0000;
}

body{
background-color:#003366;
color:#000000;
font-family:<?php echo $cfg['family1']; ?>;
font-size:<?php echo $cfg['size']; ?>;
line-height:140%;
margin:20px;
}

.ftr{
background-color:transparent;
color:#99ccff;
font-family:<?php echo $cfg['family1']; ?>;
font-size:<?php echo $cfg['size']; ?>;
}

a.ftr:hover{background-color:transparent;color:#00ffff;}

form{margin:0px;}

input,select,textarea,ul,ol,li,p,blockquote{
font-family:<?php echo $cfg['family1']; ?>;
font-size:<?php echo $cfg['size']; ?>;
}

table{
background-color:#ffffff;
color:#000000;
}

td{
padding:5px;
<?php echo $cfg['valign']; ?>
}

/**
 * td.normal available for user-added tables.
 */

td.normal{
background-color:#ffffff;
color:#000000;
padding:5px;
}

th{ /* this border inherited below */
<?php echo $opts['border_style']; ?>
font-weight:normal;
<?php echo $cfg['valign']; ?>
padding:3px;
}

/**
 * th.normal available for user-added tables.
 */

th.normal{
background-color:#ffffff;
color:#000000;
padding:10px;
}

h3{
background-color:transparent;
color:#99ccff;
font-family:<?php echo $cfg['family2']; ?>;
font-size:medium;
margin:2px 0px;
}

code,pre{
font-size:small;
}

p.code,pre.code{
background-color:<?php echo $cfg['bgcolor0']; ?>;
border:1px solid #003366;
color:#000000;
padding:5px;
}

/* table.container surrounds form.pme-form */

table.container{
background-color:#003366;
border-collapse:collapse;
border:none;
color:#000000;
}

/**
 * End default style, begin phpMyEdit-specific styles
 * 
 * TABs feature 
*/

a.pme-tab-selected:hover{background-color:transparent;color:#00ffff;}
a.pme-tab-selected{background-color:transparent;color:#00ffff;}
a.pme-tab:hover{background-color:transparent;color:#00ffff;}
a.pme-tab{background-color:transparent;color:#99ccff;}
table.pme-tab{margin-bottom:10px 5px;border-collapse:collapse;background-color:transparent;color:#000000;}
tr.pme-tab{background-color:transparent;color:#000000;}
td.pme-tab-end{padding:3px;background-color:transparent;color:#000000;}
td.pme-tab-selected{padding:3px;background-color:transparent;color:#000000;}
td.pme-tab{padding:3px;background-color:transparent;color:#000000;}

/*
Omit style for Javascript tags, style is already too complex!
*/

/*
#phpMyEdit_tab0_down_label td{}
#phpMyEdit_tab0_down_link   a{}
*/


form.pme-form{
background-color:#336699;
border:thin outset #003366;
color:#000000;
margin:0px;
padding:5px;
}

table.pme-main{
background-color:#ffffff;
border-collapse:collapse;
/*border:thin outset #6699cc;*/
color:<?php echo $cfg['fcolor1']; ?>;
}

th.pme-header{
background-color:#ffffff;
color:<?php echo $cfg['fcolor1']; ?>;
text-align:left;
white-space:nowrap;
}

th.pme-header-right-justify{
background-color:#ffffff;
color:<?php echo $cfg['fcolor1']; ?>;
text-align:right;
}

a.pme-header:hover{
background-color:transparent;
color:#ff0000;
}

.pme-clear,
.pme-hide,
.pme-search{
background-color:#003366;
border:thin outset #6699cc;
color:#ffffff;
}

.pme-sortinfo{
background-color:#cccccc;
color:<?php echo $cfg['fcolor1']; ?>;
}

tr.pme-filter{
background-color:#cccccc;
color:<?php echo $cfg['fcolor1']; ?>;
}

select.pme-filter,
select.pme-filter-right-justify{
background-color:#ffffff;
border:1px solid #003366;
color:#ff0000;
}

/*
select.pme-goto{}
*/

input.pme-filter,
input.pme-filter-right-justify{
background-color:#ffffff;
border:1px solid #003366;
color:#ff0000;
}


td.pme-filter,td.pme-filter-right-justify{
white-space:nowrap;
}


.pme-queryinfo{
background-color:#cccccc;
border:1px solid #003366;
color:<?php echo $cfg['fcolor1']; ?>;
}

a.pme-navigation-0,
a.pme-navigation-1{
background-color:transparent;
color:#003366;
}

a.pme-navigation-0:hover,
a.pme-navigation-1:hover{
background-color:transparent;
color:#ff0000;
}

td.pme-navigation-0{
<?php echo $opts['border_style']; ?>
background-color:<?php echo $cfg['bgcolor0']; ?>;
color:<?php echo $cfg['fcolor1']; ?>;
white-space:nowrap;
}

td.pme-navigation-1{
<?php echo $opts['border_style']; ?>
background-color:<?php echo $cfg['bgcolor1']; ?>;
color:<?php echo $cfg['fcolor1']; ?>;
white-space:nowrap;
}

table.pme-navigation{
border-collapse:collapse;
/*border:thin outset #6699cc;*/
}

tr.pme-navigation{
background-color:<?php echo $cfg['row_nav_bgcolor']; ?>;
color:<?php echo $cfg['fcolor1']; ?>;
}

a.pme-cell-0,
a.pme-cell-1,
a.pme-value-0,
a.pme-value-1{
background-color:transparent;
color:<?php echo $cfg['fcolor3']; ?>;
}

input.pme-last,
input.pme-last,
input.pme-add,
input.pme-first,
input.pme-goto,
input.pme-cancel,
input.pme-change,
input.pme-copy,
input.pme-delete,
input.pme-more,
input.pme-navigation-0,
input.pme-navigation-1,
input.pme-next,
input.pme-prev,
input.pme-save,
input.pme-search,
input.pme-view{
background-color:#003366;
border:thin outset #6699cc;
color:#ffffff;
}

input.pme-query{
background-color:#003366;
color:#ffffff;
}

input.pme-input-0-right-justify,
input.pme-input-0{
background-color:#ffffff;
color:<?php echo $cfg['fcolor1']; ?>;
}

input.pme-input-1-right-justify,
input.pme-input-1{
background-color:#ffffff;
color:<?php echo $cfg['fcolor1']; ?>;
}

textarea.pme-input-0,
textarea.pme-input-1{
background-color:#ffffff;
color:<?php echo $cfg['fcolor1']; ?>;
}

select.pme-input-0,
select.pme-input-1{
background-color:#ffffff;
color:<?php echo $cfg['fcolor1']; ?>;
}

td.pme-cell-0,
td.pme-cell-1{
<?php echo $opts['border_style']; ?>
}

td.pme-sortinfo{
<?php echo $opts['border_style']; ?>
}

td.pme-cell-0-right-justify,
td.pme-cell-1-right-justify{
<?php echo $opts['border_style']; ?>
text-align:right;
}

td.pme-buttons{
background-color:#336699;
color:#ffffff;
vertical-align:middle;
white-space:nowrap;
}

td.pme-message,
td.pme-stats{
background-color:#336699;
color:#ffffff;
vertical-align:middle;
}

tr.pme-row-0,
tr.pme-row-0-right-justify{
background-color:<?php echo $cfg['bgcolor0']; ?>;
color:<?php echo $cfg['fcolor1']; ?>;
}

tr.pme-row-1,
tr.pme-row-1-right-justify{
background-color:<?php echo $cfg['bgcolor1']; ?>;
color:<?php echo $cfg['fcolor1']; ?>;
}

td.pme-help-0-right-justify,
td.pme-help-0{
background-color:<?php echo $cfg['bgcolor0']; ?>;
border-bottom:1px solid <?php echo $cfg['bdr_bot_color']; ?>;
color:<?php echo $cfg['fcolor4']; ?>;
<?php echo $cfg['valign']; ?>
}

td.pme-help-1-right-justify,
td.pme-help-1{
background-color:<?php echo $cfg['bgcolor1']; ?>;
border-bottom:1px solid <?php echo $cfg['bdr_bot_color']; ?>;
color:<?php echo $cfg['fcolor4']; ?>;
<?php echo $cfg['valign']; ?>
}

td.pme-key-0-right-justify,
td.pme-key-0,
td.pme-value-0-right-justify,
td.pme-value-0{
background-color:<?php echo $cfg['bgcolor0']; ?>;
border-bottom:1px solid <?php echo $cfg['bdr_bot_color']; ?>;
color:<?php echo $cfg['fcolor1']; ?>;
<?php echo $cfg['valign']; ?>
}

td.pme-key-1-right-justify,
td.pme-key-1,
td.pme-value-1-right-justify,
td.pme-value-1{
background-color:<?php echo $cfg['bgcolor1']; ?>;
border-bottom:1px solid <?php echo $cfg['bdr_bot_color']; ?>;
color:<?php echo $cfg['fcolor1']; ?>;
<?php echo $cfg['valign']; ?>
}

hr,hr.pme-hr{
background-color:transparent;
color:#003366;
height:1px;
}

img.pme-navigation-0,img.pme-navigation-1{
margin:0px 0px 0px 3px;
text-align:center;
white-space:nowrap;
}

.contrast{
background-color:transparent;
color:#00ffff;
}

-->
</style>

