<?php

/**
 * You may find it useful to define a library of 
 * arrays and then include the library in your forms. 
 * Edit, add, or delete arrays based on your needs.
 * $opts['fdd']['country']['values'] = $countries;
 */

$ny = array('', 'N', 'Y');

$no_yes = array('', 'No', 'Yes');

$yn = array('', 'Y', 'N');

$yes_no = array('', 'Yes', 'No');

$months1 = array('', '01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12');

$months2 = array('', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12');

$months3 = array( '', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'};

$months4 = array( '', 'January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'};

$days1 = array('', '01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31');

$days2 = array('', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31');

$years = array(date('Y'), date('Y')+1, date('Y')+2, date('Y')+3, date('Y')+4);

$alpha1 = array('A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z');

$alpha2 = array('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z');

$my_range = range(0, 100);

$weekdays = array( '', 'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday');

$surname_suffix = array( '', 'CEO', 'Esq', 'III', 'Jr', 'MD', 'PhD', 'Sr');

$salutation = array( '', 'Doctor', 'Mr.', 'Mrs.', 'Ms.', 'Professor');

$us_states1 = array(
	'',
	'Alabama',
	'Alaska',
	'Arizona',
	'Arkansas',
	'California',
	'Colorado',
	'Connecticut',
	'Delaware',
	'Dist. of Columbia',
	'Florida',
	'Georgia',
	'Hawaii',
	'Idaho',
	'Illinois',
	'Indiana',
	'Iowa',
	'Kansas',
	'Kentucky',
	'Louisiana',
	'Maine',
	'Maryland',
	'Massachusetts',
	'Michigan',
	'Minnesota',
	'Mississippi',
	'Missouri',
	'Montana',
	'Nebraska',
	'Nevada',
	'New Hampshire',
	'New Jersey',
	'New Mexico',
	'New York',
	'North Carolina',
	'North Dakota',
	'Ohio',
	'Oklahoma',
	'Oregon',
	'Pennsylvania',
	'Rhode Island',
	'South Carolina',
	'South Dakota',
	'Tennessee',
	'Texas',
	'Utah',
	'Vermont',
	'Virginia',
	'Washington',
	'West Virginia',
	'Wisconsin',
	'Wyoming'
);


$us_states2 = array('', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IA', 'ID', 'IL', 'IN', 'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH', 'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA', 'VT', 'WA', 'WI', 'WV', 'WY');

$countries = array(
	'Afghanistan', 
	'Albania', 
	'Algeria', 
	'American Samoa', 
	'Andorra', 
	'Angola', 
	'Antarctica', 
	'Antigua & Barbuda', 
	'Argentina', 
	'Armenia', 
	'Aruba', 
	'Australia', 
	'Austria', 
	'Azerbaijan', 
	'Bahamas', 
	'Bahrain', 
	'Bangladesh', 
	'Barbados', 
	'Belarus', 
	'Belgium', 
	'Belize', 
	'Benin', 
	'Bermuda', 
	'Bhutan', 
	'Bolivia', 
	'Bosnia & Herzegovina', 
	'Botswana', 
	'Bouvet Island', 
	'Brazil', 
	'British Antarctica Territory', 
	'British Indian Ocean Territory', 
	'British West Indies', 
	'Brunei', 
	'Bulgaria', 
	'Burundi', 
	'Caledonia', 
	'Cambodia', 
	'Cameroon', 
	'Canada', 
	'Canary Islands', 
	'Canton And Enderbury Islands', 
	'Cape Verdi Islands', 
	'Cayman Islands', 
	'Central African Republic', 
	'Chad', 
	'Channel Islands UK', 
	'Chile', 
	'China', 
	'Christmas Island', 
	'Cocos (Keeling) Islands', 
	'Colombia', 
	'Comoros', 
	'Congo - Republic of', 
	'Cook Islands', 
	'Costa Rica', 
	'Croatia', 
	'Cuba', 
	'Curacao', 
	'Cyprus', 
	'Czech Republic', 
	'Dahomey', 
	'Dem. People\'s Republic of Korea', 
	'Dem. Republic of Vietnam', 
	'Denmark', 
	'Djibouti', 
	'Dominica', 
	'Dominican Republic', 
	'Dronning Muad Land - Antarctica', 
	'Ecuador', 
	'Egypt', 
	'El Salvador', 
	'England, UK', 
	'Equatorial Guinea', 
	'Estonia', 
	'Ethiopia', 
	'Faeroe Islands', 
	'Falkland Islands', 
	'Fiji', 
	'Finland', 
	'France', 
	'French Guiana', 
	'French Polynesia', 
	'French Southern & Antarctica', 
	'French Territory of Afars & Issas', 
	'French West Indies', 
	'Gabon', 
	'Gambia', 
	'Gaza', 
	'Georgia', 
	'Germany', 
	'Ghana', 
	'Gibraltar', 
	'Greece', 
	'Greenland', 
	'Guadeloupe', 
	'Guam', 
	'Guatemala', 
	'Guinea', 
	'Guinea Bissau', 
	'Guyana', 
	'Haiti', 
	'Heard & McDonald Islands', 
	'Holland', 
	'Honduras', 
	'Hong Kong', 
	'Hungary', 
	'Iceland', 
	'Ifni', 
	'India', 
	'Indonesia', 
	'Iran', 
	'Iraq', 
	'Iraq-Saudi Arabia Neutral Zone', 
	'Ireland', 
	'Israel', 
	'Italy', 
	'Ivory Coast', 
	'Jamaica', 
	'Japan', 
	'Johnston Atoll', 
	'Jordan', 
	'Kazakhstan', 
	'Kenya', 
	'Kuwait', 
	'Kyrgyzstan', 
	'Laos', 
	'Latvia', 
	'Lebanon', 
	'Leeward Islands', 
	'Lesotho', 
	'Liberia', 
	'Libya', 
	'Liechtenstein', 
	'Lithuania', 
	'Luxembourg', 
	'Macau', 
	'Madagascar', 
	'Malawi', 
	'Malaysia', 
	'Maldives', 
	'Mali', 
	'Malta', 
	'Mariana Islands', 
	'Martinique', 
	'Mauritania', 
	'Mauritius', 
	'Melanesia', 
	'Mexico', 
	'Micronesia', 
	'Midway Islands', 
	'Moldova', 
	'Monaco', 
	'Mongolia', 
	'Montenegro', 
	'Montserrat', 
	'Morocco', 
	'Mozambique', 
	'Myanmar', 
	'Namibia', 
	'Nauru', 
	'Navassa Island', 
	'Nepal', 
	'Netherlands', 
	'Netherlands Antilles', 
	'Neutral Zone', 
	'New Hebrides', 
	'New Zealand', 
	'Nicaragua', 
	'Niger', 
	'Nigeria', 
	'Niue', 
	'Norfolk Island', 
	'North Korea', 
	'Northern Ireland, UK', 
	'Norway', 
	'Oman', 
	'Pacific Island', 
	'Pakistan', 
	'Panama', 
	'Papua New Guinea', 
	'Paracel Islands', 
	'Paraguay', 
	'Peru', 
	'Philippines', 
	'Pitcairn', 
	'Poland', 
	'Polynesia', 
	'Portugal', 
	'Portuguese Guinea', 
	'Portuguese Timor', 
	'Principe & Sao Tome', 
	'Puerto Rico', 
	'Qatar', 
	'Republic of Congo', 
	'Republic of Korea', 
	'Reunion', 
	'Romania', 
	'Russia', 
	'Rwanda', 
	'Ryukyu Islands', 
	'Sabah', 
	'San Marino', 
	'Sao Tome & Principe', 
	'Saudi Arabia', 
	'Scotland, UK', 
	'Senegal', 
	'Serbia', 
	'Seychelles', 
	'Sierra Leone', 
	'Sikkim', 
	'Singapore', 
	'Slovakia', 
	'Slovenia', 
	'Solomon Islands', 
	'Somalia', 
	'Somaliliand', 
	'South Africa', 
	'South Korea', 
	'Spain', 
	'Spanish Sahara', 
	'Spartly Islands', 
	'Sri Lanka', 
	'St. Christopher-Nevis-Anguilla', 
	'St. Helena', 
	'St. Kitts', 
	'St. Lucia', 
	'St. Pierre & Miquelon', 
	'St. Vincent', 
	'Sudan', 
	'Surinam', 
	'Svalbard & Jan Mayen Islands', 
	'Swaziland', 
	'Sweden', 
	'Switzerland', 
	'Syrian Arab Republic', 
	'Taiwan', 
	'Tanzania', 
	'Thailand', 
	'Togo', 
	'Tonga', 
	'Transkei', 
	'Trinidad/Tobago', 
	'Tunisia', 
	'Turkey', 
	'Turkmenistan', 
	'Turks & Caicos Islands', 
	'Uganda', 
	'Ukraine', 
	'United Arab Emirates', 
	'United Kingdom', 
	'United States', 
	'Uruguay', 
	'US Pacific Island', 
	'US Virgin Islands', 
	'Uzbekistan', 
	'Vanuatu', 
	'Vatican City', 
	'Venezuela', 
	'Vietnam', 
	'Virgin Islands (British)', 
	'Virgin Islands (US)', 
	'Wake Island', 
	'Wales, UK', 
	'West Indies', 
	'Western Samoa', 
	'Windward Islands', 
	'Yemen', 
	'Zambia', 
	'Zimbabwe'
);

$fives = array('', '05', '10', '15', '20', '25', '30', '35', '40', '45', '50');

$num-01 = array('0', '1');

$num-09 = array('0', '1', '2', '3', '4', '5', '6', '7', '8', '9');

$num-10 = array('', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10');

$num-120 = array('', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '12', '13', '14', '15', '16', '17', '18', '19', '20');


?>
